# Map directory of zshrc_files
DIR="${$(readlink ~/.zshrc)%??????????}"

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# or, alternatively, ~/.oh-my-zsh/custom/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="brm"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git brew npm last-working-dir)

# source oh-my-zsh
source $ZSH/oh-my-zsh.sh

# Source all .zsh files
for files in ${DIR}/**/*.zsh; do source $files; done

# Alternatively you can choose to load .zsh files manually

# source ${DIR}/sublime_text/sublime.zsh
# source ${DIR}/ohmyzsh/settings.zsh
# ...
